In [20]:
# for computing factorials from a user input

num = int(input("number for factorial: "))
factorial = 1
for i in range(1,num+1):
    factorial *= i
print (factorial)


number for factorial: 3
6


In [35]:
hello = [3]
lst = hello.pop()
print(lst)

3


In [36]:
hello.append(15)
hello += [4,5,6]
print(hello)

[15, 4, 5, 6]


In [39]:
hello.insert(3,54)
print(hello)

[15, 4, 54, 54, 6]


In [38]:
hello.pop(2)
print(hello)

[15, 4, 54, 6]


In [40]:
hello.index(54)

2

In [41]:
hello.count(54)

2

In [47]:
[num if num==2 else num/2 for num in hello]

[7.5, 2.0, 27.0, 27.0, 3.0]

In [49]:
new_list = [num for num in range (2,21)]
print (new_list)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [56]:
print ([num*2 if num%2==1 else num for num in new_list])
print ([num*2 for num in new_list if num%2==1])
print ([num*6 if num%3==0 else num/2 for num in new_list])

[2, 6, 4, 10, 6, 14, 8, 18, 10, 22, 12, 26, 14, 30, 16, 34, 18, 38, 20]
[6, 10, 14, 18, 22, 26, 30, 34, 38]
[1.0, 18, 2.0, 2.5, 36, 3.5, 4.0, 54, 5.0, 5.5, 72, 6.5, 7.0, 90, 8.0, 8.5, 108, 9.5, 10.0]


In [70]:
G = 6.67e-11

def f_of_g(mass1, mass2, r):
    f = G*(abs(mass1*mass2)/r**2)
    return f

print(f_of_g(-20,40,r=40))

3.335e-11


In [68]:
new_list = [50,62,74,80,85,100]

def average_finder(*args):
    addition = 0
    for num in args:
        addition += num
    return addition/len(args)

average_finder(*new_list)

75.16666666666667

In [69]:
new_list2 = [2,5,8,9]

double = lambda x: 2*x

list(map(double,new_list2))

[4, 10, 16, 18]

In [3]:
import seaborn
import pandas
import matplotlib


In [72]:
!pip install pyfiglet

     |████████████████████████████████| 865 kB 2.4 MB/s eta 0:00:01


In [5]:
import numpy as np
np.logspace(1,2,2)

array([ 10., 100.])

In [8]:
arr = np.arange(1,31)
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [12]:
slice_of = arr[2:7]
slice_of[:] = 999

array([  1,   2, 999, 999, 999, 999, 999,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30])

In [14]:
arr[3] = 23
slice_of

array([999,  23, 999, 999, 999])